###############################################################################

- name: dependencies
  apt:
    pkg:
    - monit
    - ruby
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- hmac_sha256_signature:
    message: monit
    secret: '{{ci_master_secret}}'
  register: monit_password_signature

- set_fact:
    monit_password: '{{monit_password_signature.signature}}'

- include: monitor-service.yml
  with_dict: '{{ci_server_services}}'

- name: enable and start monit
  service:
    name: monit
    state: started
    enabled: yes

- name: reload monit
  service:
    name: monit
    state: reloaded
    enabled: yes
