- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: [ntpdate, ntp]
  when: setup_ntp

- name: configure ntp server
  lineinfile:
    dest: /etc/ntp.conf
    line: 'pool {{ntp_server}}'
    regexp: '^pool*$'
  when: setup_ntp

- name: run initial ntpdate
  shell:
    #!/bin/bash
    set -eux
    systemctl stop ntp
    ntpdate {{ntp_server}}
    systemctl start ntp
  when: setup_ntp

