- name: Add pgdg apt key
  apt_key:
    id: ACCC4CF8
    url: http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  tags: [internet]

- name: Add pgdg apt repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main
  tags: [internet]

- name: Install postgresql
  apt:
    pkg:
    - sudo
    - libpq-dev
    - postgresql-client-{{ci_executor_trait_postgresql_version_major}}
    - postgresql-contrib-{{ci_executor_trait_postgresql_version_major}}
    - postgresql-{{ci_executor_trait_postgresql_version_major}}
    - python3-psycopg2
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

