- include_tasks: install.yml

- include_tasks: configure.yml
  tags: [ci_executor_trait_postgresql_configure]

- file:
    path: ~{{ci_executor_trait_postgresql_exec_user}}/.bash_login.d/postgresql.sh
    state: absent

- name: Env for the user
  template:
    src: pgenv.sh
    dest: ~{{ci_executor_trait_postgresql_exec_user}}/.bash_login.d/postgresql{{ci_executor_trait_postgresql_version_major}}.sh
    owner: root
    group: '{{ci_executor_trait_postgresql_exec_user}}'
    mode: 0640


- name: register postgresql trait
  register_traits:
    traits:
      - PostgreSQL
      - PostgreSQL {{ci_executor_trait_postgresql_version}}
    file: /cider-ci/executor/config/traits.yml
