- name: Install vagrant
  apt:
    pkg: vagrant
    state: latest
    cache_valid_time: 3600
  tags: [internet]

- name: register vagrant trait
  register_traits:
    traits:
      - vagrant
    file: /etc/cider-ci/traits.yml
