- apt:
    pkg:
    - curl
    - graphviz
    - hunspell
    - hunspell-de-ch
    - hunspell-de-de
    - hunspell-en-us
    - hunspell-tools
    - imagemagick
    - libgconf-2-4
    - libimage-exiftool-perl
    - xvfb
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- name: register traits
  register_traits:
    traits:
    - ExifTool
    - Graphviz
    - Hunspell
    - Hunspell DE-CH
    - Hunspell DE-DE
    - Hunspell EN-US
    - ImageMagick
    - Xvfb
    - curl
    - libgconf-2-4
    file: /etc/cider-ci/traits.yml
