- hosts: cider-ci_executors
  gather_facts: False
  pre_tasks:
  - name: install system python
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python)

- hosts: cider-ci_server

  roles:

  - role: debug
    tags: [debug]

- hosts: cider-ci_executors

  pre_tasks: []

  roles:

  - role: debug
    tags: [debug]

  - role: os-setup
    tags: [os-setup]

  - role: openjdk8_install
    tags: [openjdk8_install]

  - role: executors-roles/prepare
    tags: [executors_perpare]

  - role: executors-roles/exec-user
    tags: [executors_exec-user]

  - role: executors-roles/deploy
    tags: [executors_deploy]
