- hosts: cider-ci_executors

  vars_files:
  - '{{inventory_dir}}/config.yml'

  pre_tasks: []

  roles:

  - role: debug
    tags: [debug]

  - role: os-setup
    tags: [os-setup]

  - role: openjdk8_install
    tags: [openjdk8_install]

  - role: executors-roles/prepare
    tags: [executors_perpare]

  - role: executors-roles/exec-user
    tags: [executors_exec-user]

  - role: executors-roles/deploy
    tags: [executors_deploy]
