### Prepare machines ##########################################################

- hosts: all
  vars_files:
    - vars.yml
    - "{{ vars_local | default('vars.yml') }}"

  roles:
    - role: prepare-all
      tags: [prepare-all]

### Clean slate ###############################################################

- hosts: all
  vars_files:
    - vars.yml
  roles:
    - role: clean-slate
      when: clean_slate
      tags: [clean-slate]

### Server ####################################################################

- include: play_server.yml

### executors #################################################################

- include: play_executors.yml

