###############################################################################
### executors #################################################################
###############################################################################

# we need to query the server once to access vars
- hosts: cider-ci-server
  tasks:
  - setup: {}

- hosts: cider-ci-executors

  vars_files:
    - vars.yml
    - vars-server.yml
    - vars-executors.yml
    - "{{ vars_local | default('vars.yml') }}"


  tasks:

  roles:

    - role: git-checkout
      git_checkout_target_path: '/var/local/cider-ci'
      git_checkout_repo: "{{cider_ci_repo}}"
      git_checkout_version: "{{ lookup('pipe','cd  ./../. && git log -n 1 --format=%H') }}"
      tags: [git-checkout]

    - role: executor-secrets
      tags: [executor-secrets]

    - role: executor-user
      user: '{{executor_execution_user}}'
      tags: [executor-user]

    - role: executor-config
      tags: [executor-config]

    - role: lein-service
      lein_service_name: cider-ci_executor
      lein_service_app_dir: /var/local/cider-ci/executor
      lein_service_user: root
      tags: [lein-service]

    - role: nightly-reboot
      tags: [nightly-reboot]
