### Prepare machines ##########################################################

- hosts: [cider-ci-server, cider-ci-executors-linux]
  vars_files:
    - vars.yml
    - "{{ vars_local | default('vars.yml') }}"

  roles:
  - role: prepare-all
    tags: [prepare-all]

### Server ####################################################################

- include: play_server.yml

### executors #################################################################

- include: play_executors-linux.yml

- include: play_executors-windows.yml

### traits for linux executors ################################################

- include: play_traits_executors-linux.yml
