- hosts: cider-ci-server

  vars_files:
    - vars.yml

  tasks:

  - debug:
      var: ansible_memtotal_mb

  - debug:
      var: ci_memtotal_mb

  - debug:
      var: user_interface_xmx_mb_value

  - debug:
      var: cider_ci_master_secret

  - debug:
      var: cider_ci_database_secret

  - debug:
      var: secret_key_base

  - debug:
      var: cider_ci_mq_secret
