- hosts: cider-ci-server
  vars_files:
    - vars.yml
    - vars-server.yml
    - "{{ vars_local | default('vars.yml') }}"
  tasks:
    - set_fact:
       server_host: "{{ansible_default_ipv4.address}}"

- hosts: cider-ci-executors-linux

  tags: [traits]

  vars_files:
    - vars.yml
    - vars-executors.yml
    - "{{ vars_local | default('vars.yml') }}"

  roles:

    - role: traits/roles/defaults
      when: "'defaults' in traits"

    - role: traits/roles/nodejs
      when: "'nodejs' in traits"

    - role: traits/roles/curl
      when: "'curl' in traits"

    - role: traits/roles/imagemagick
      when: "'imagemagick' in traits"

    - role: traits/roles/chrome-and-chromedriver
      when: "'chrome-and-chromedriver' in traits"

    - role: traits/roles/firefox
      when: "'firefox' in traits and ( ansible_distribution != 'Debian' )"

    - role: traits/roles/firefox-esr
      when: "'firefox-esr' in traits"

    - role: traits/roles/phantomjs
      when: "'phantomjs' in traits"

    - role: traits/roles/tightvnc
      when: "'tightvnc' in traits"

    - role: traits/roles/openjdk
      when: "'openjdk' in traits"

    - role: traits/roles/maven
      when: "'maven' in traits"

    - role: traits/roles/leiningen
      when: "'leiningen' in traits"

    - role: traits/roles/postgresql
      when: "'postgresql' in traits"

    - role: traits/roles/mysql
      when: "'mysql' in traits"

    - role: traits/roles/sqlite3
      when: "'sqlite3' in traits"

    - role: traits/roles/rabbitmq
      when: "'rabbitmq' in traits"

    - role: traits/roles/rbenv
      when: "'rbenv' in traits"

    - role: traits/roles/jruby-9000
      when: "'jruby-9000' in traits"

    - role: traits/roles/jruby-1.7
      when: "'jruby-1.7' in traits"

    - role: traits/roles/ruby-2.1
      when: "'ruby-2.1' in traits"

    - role: traits/roles/ruby-2.2
      when: "'ruby-2.2' in traits"

    - role: traits/roles/ansible
      when: "'ansible' in traits"

    - role: traits/roles/mkdocs
      when: "'mkdocs' in traits"

    - role: traits/roles/git
      when: "'git' in traits"

    - role: traits/roles/exiftool
      when: "'exiftool' in traits"

    - role: traits/roles/bower
      when: "'bower' in traits"
      tags: ['bower']
