### Prepare machines ##########################################################
- hosts: all
  vars_files:
    - vars.yml
    - "{{ vars_local | default('vars.yml') }}"

  roles:
    - role: prepare-all

###############################################################################
### Clean slate ###############################################################
###############################################################################

- hosts: all
  vars_files:
    - vars.yml
  roles:
    - role: clean-slate
      when: clean_slate


###############################################################################
### Server phase 1 ############################################################
###############################################################################

- hosts: cider-ci-server
  vars_files:
    - vars.yml
    - vars-server.yml
    - "{{ vars_local | default('vars.yml') }}"
  roles:

    - role: server-apache2

    - role: server-reverse-proxy
      reverse_proxy_enabled: False

    - role: server-monitoring
      monitoring_state: unmonitored
      monit_state: stopped
      monitored_services: "{{cider_ci_server_services}}"
      tags: [debug]

    - role: server-shutdown-services
      tags: [debug]

###############################################################################
### executors #################################################################
###############################################################################

- hosts: cider-ci-executors

  vars_files:
    - vars.yml
    - vars-server.yml
    - vars-executors.yml
    - "{{ vars_local | default('vars.yml') }}"

  roles:


    - role: git-checkout
      git_checkout_target_path: '/var/local/cider-ci'
      git_checkout_repo: "{{cider_ci_repo}}"
      git_checkout_version: "{{ lookup('pipe','cd  ./../. && git log -n 1 --format=%H') }}"

    - role: executor-secrets

    - role: executor-user
      user: '{{executor_execution_user}}'

    - role: executor-config

    - role: lein-service
      lein_service_name: cider-ci_executor
      lein_service_app_dir: /var/local/cider-ci/executor
      lein_service_user: root

    - role: nightly-reboot


###############################################################################
### server phase 2 ############################################################
###############################################################################


- hosts: cider-ci-server
  vars_files:
    - vars.yml
    - vars-server.yml
    - "{{ vars_local | default('vars.yml') }}"

  roles:

    - role: git-checkout
      git_checkout_target_path: '/var/local/cider-ci'
      git_checkout_repo: "{{cider_ci_repo}}"
      git_checkout_version: "{{ lookup('pipe','cd  ./../. && git log -n 1 --format=%H') }}"

    - role: postgresql
      postgresql_version: 9.4
      port: 5432

    - role: rabbitmq

    - role: server-common

    - role: user-interface


    # TODO: lots of duplication here, ideally we would use
    #   with_items: "{{cider_ci_server_services}}"
    # but it doesn't work with roles for now, there seems
    # to be coming something in Ansible v2

    - role: lein-service
      lein_service_name: cider-ci_api
      lein_service_app_dir: /var/local/cider-ci/api
      lein_service_user: cider-ci_api

    - role: lein-service
      lein_service_name: cider-ci_builder
      lein_service_app_dir: /var/local/cider-ci/builder
      lein_service_user: cider-ci_builder

    - role: lein-service
      lein_service_name: cider-ci_dispatcher
      lein_service_app_dir: /var/local/cider-ci/dispatcher
      lein_service_user: cider-ci_dispatcher

    - role: lein-service
      lein_service_name: cider-ci_notifier
      lein_service_app_dir: /var/local/cider-ci/notifier
      lein_service_user: cider-ci_notifier

    - role: lein-service
      lein_service_name: cider-ci_repository
      lein_service_app_dir: /var/local/cider-ci/repository
      lein_service_user: cider-ci_repository

    - role: lein-service
      lein_service_name: cider-ci_storage
      lein_service_app_dir: /var/local/cider-ci/storage
      lein_service_user: cider-ci_storage


    - role: db-backups

    - role: server-set-data

    - role: server-reverse-proxy

    - role: server-check-services

    - role: server-monitoring
      monitoring_state: monitored
      monitored_services: "{{cider_ci_server_services}}"
      tags: [monit]
