- include: build_play.yml

- hosts: cider-ci_server

  vars_files:
  - '{{inventory_dir}}/config.yml'

  pre_tasks: []

  roles:

  - role: debug
    tags: [debug]

  - role: os-setup
    tags: [os-setup]

  - role: openjdk8_install
    tags: [openjdk8_install]

  - role: server-roles/get-archive
    tags: [get-archive]

  - role: server-roles/prepare
    tags: [prepare]

  - role: server-roles/postgresql
    tags: [postgresql]

  - role: server-roles/rabbitmq
    tags: [rabbitmq]

  - role: server-roles/deploy
    tags: [deploy]

  - role: server-roles/reverse-proxy
    tags: [server_reverse-proxy]

  - role: server-roles/monitoring
    tags: [server_monitoring]

  - role: server-roles/data-import
    tags: [server_import-data]
