###############################################################################
### these are meant to be customized ##########################################
###############################################################################

ci_external_hostname: '{{ ansible_default_ipv4.address }}'
ci_base_url: http://{{ ci_external_hostname }}

ci_virtual_hosts:
- hostname: "{{ ci_internal_hostname }}"
  ip: "{{ ci_internal_hostname }}"
- hostname: NULL
  ip: '*'
  ssl_certificate_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
  ssl_certificate_key_file: /etc/ssl/private/ssl-cert-snakeoil.key


server_timezone: Etc/UTC
rails_timezone: UTC

  #- hostname: NULL
  #ssl_certificate_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
  #ssl_certificate_key_file: /etc/ssl/private/ssl-cert-snakeoil.key


### Secrets ###################################################################

ci_database_secret: "{{ [ci_master_secret, 'ci_database_secret', ci_master_secret ] | join(' ') | hash('sha256') }}"
ci_messaging_secret: "{{ [ci_master_secret, 'ci_messaging_secret', ci_master_secret ] | join(' ') | hash('sha256') }}"
ci_services_secret: "{{ [ci_master_secret, 'ci_services_secret', ci_master_secret ] | join(' ') | hash('sha256') }}"


###############################################################################
### there should only rarely be the need to change any of the following #######
###############################################################################

ci_internal_hostname: localhost

ci_postgres_port: 9432
ci_trait_rabbitmq_node_port: 5673
ci_rabbitmq_mangement_port: 15673

ci_server_dir: /cider-ci/server
ci_web_context: /cider-ci

ci_services:

  ui:
    name: user-interface
    type: rails
    path: /user-interface
    http_port: 8880
    context: /ui
    max_memory_fraction: 0.40
    cache_store_size_fraction: 0.05

  api:
    name: api
    type: java
    path: /api
    http_port: 8885
    context: /api
    main: cider_ci.api.main

  builder:
    name: builder
    type: java
    path: /builder
    http_port: 8884
    context: /builder
    main: cider_ci.builder.main

  dispatcher:
    name: dispatcher
    type: java
    path: /dispatcher
    http_port: 8882
    context: /dispatcher
    main: cider_ci.dispatcher.main

  notifier:
    name: notifier
    type: java
    path: /notifier
    http_port: 8887
    context: /notifier
    main: cider_ci.notifier.main

  repository:
    name: repository
    type: java
    path: /repository
    http_port: 8881
    context: /repositories
    main: cider_ci.repository.main

  storage:
    name: storage
    type: java
    path: /storage
    http_port: 8886
    main: cider_ci.storage.main
