- hosts: cider-ci_executors

  tasks:
    - register_traits:
        traits: '{{ci_executor_custom_traits}}'
        file: /etc/cider-ci/traits.yml
      tags:
        - custom_traits

  roles:

  - role: os-setup
    tags: [os-setup]

  - role: traits/basics
    tags: [basics]

  - role: debug
    tags: [debug]

  - role: traits/ansible
    when: ci_executor_trait_ansible
    tags: ci_executor_trait_ansible

  - role: traits/apache2
    when: ci_executor_trait_apache2
    tags: ci_executor_trait_apache2

  - role: traits/asdf
    when: ci_executor_trait_asdf
    tags: ci_executor_trait_asdf

  - role: traits/asdf-nodejs
    when: ci_executor_trait_asdf_nodejs
    tags: ci_executor_trait_asdf_nodejs

  - role: traits/asdf-ruby
    when: ci_executor_trait_asdf_ruby
    tags: ci_executor_trait_asdf_ruby

  - role: traits/docker
    when: ci_executor_trait_docker
    tags: ci_executor_trait_docker

  - role: traits/git-crypt
    when: ci_executor_trait_git_crypt
    tags: ci_executor_trait_git_crypt

  - role: traits/gpg
    when: ci_executor_trait_gpg
    tags: ci_executor_trait_gpg

  - role: traits/firefox-esr
    when: ci_executor_trait_firefox_esr
    tags: ci_executor_trait_firefox_esr

  - role: traits/leiningen
    when: ci_executor_trait_leiningen
    tags: ci_executor_trait_leiningen

  - role: traits/lxd
    when: ci_executor_trait_lxd
    tags: ci_executor_trait_lxd

  - role: traits/misc
    when: ci_executor_trait_misc
    tags: ci_executor_trait_misc

  - role: traits/nodejs
    when: ci_executor_trait_nodejs
    tags: ci_executor_trait_nodejs

  - role: traits/openjdk
    when: ci_executor_trait_openjdk
    tags: ci_executor_trait_openjdk

  - role: traits/postgresql1x
    vars:
      ci_executor_trait_postgresql_version_major: 10
    when: ci_executor_trait_postgresql10
    tags: ci_executor_trait_postgresql10

  - role: traits/postgresql1x
    vars:
      ci_executor_trait_postgresql_version_major: 11
    when: ci_executor_trait_postgresql11
    tags: ci_executor_trait_postgresql11

  - role: traits/python3
    when: ci_executor_trait_python3
    tags: ci_executor_trait_python3

  - role: traits/sqlite
    when: ci_executor_trait_sqlite
    tags: ci_executor_trait_sqlite

  - role: traits/ssh-keys
    when: ci_executor_trait_ssh_keys
    tags: ci_executor_trait_ssh_keys

  - role: traits/stress-ng
    when: ci_executor_trait_stress_ng
    tags: ci_executor_trait_stress_ng

  - role: traits/translation-tools
    when: ci_executor_trait_translation_tools
    tags: ci_executor_trait_translation_tools

  - role: traits/ubuntu-desktop
    when: ci_executor_trait_ubuntu_desktop
    tags: ci_executor_trait_ubuntu_desktop

  - role: traits/xorg
    when: ci_executor_trait_xorg
    tags: ci_executor_trait_xorg

  - role: traits/wine
    when: ci_executor_trait_wine
    tags: ci_executor_trait_wine
