- hosts: cider-ci_executors

  pre_tasks: []

  roles:

  - role: debug
    tags: [debug]

  - role: traits/ansible
    when: ci_executor_trait_ansible
    tags: ci_executor_trait_ansible

  - role: traits/apache2
    when: ci_executor_trait_apache2
    tags: ci_executor_trait_apache2

  - role: traits/bower
    when: ci_executor_trait_bower
    tags: ci_executor_trait_bower

  - role: traits/chruby
    when: ci_executor_trait_chruby
    tags: ci_executor_trait_chruby

  - role: traits/git-crypt
    when: ci_executor_trait_git_crypt
    tags: ci_executor_trait_git_crypt

  - role: traits/firefox-esr
    when: ci_executor_trait_firefox_esr
    tags: ci_executor_trait_firefox_esr

  - role: traits/leiningen
    when: ci_executor_trait_leiningen
    tags: ci_executor_trait_leiningen

  - role: traits/lxd
    when: ci_executor_trait_lxd
    tags: ci_executor_trait_lxd

  - role: traits/misc
    when: ci_executor_trait_misc
    tags: ci_executor_trait_misc

  - role: traits/mysql
    when: ci_executor_trait_mysql
    tags: ci_executor_trait_mysql

  - role: traits/nodejs
    when: ci_executor_trait_nodejs
    tags: ci_executor_trait_nodejs

  - role: traits/openjdk
    when: ci_executor_trait_openjdk
    tags: ci_executor_trait_openjdk

  - role: traits/phantomjs
    when: ci_executor_trait_phantomjs
    tags: ci_executor_trait_phantomjs

  - role: traits/postgresql
    when: ci_executor_trait_postgresql
    tags: ci_executor_trait_postgresql

  - role: traits/rbenv
    when: ci_executor_trait_rbenv
    tags: ci_executor_trait_rbenv

  - role: traits/ruby-install
    when: ci_executor_trait_ruby_install
    tags: ci_executor_trait_ruby_install

  - role: traits/sqlite
    when: ci_executor_trait_sqlite
    tags: ci_executor_trait_sqlite

  - role: traits/stress-ng
    when: ci_executor_trait_stress_ng
    tags: ci_executor_trait_stress_ng
