- hosts: cider-ci_executors

  pre_tasks:
  - register_traits:
      traits: '{{ci_executor_custom_traits}}'
      file: /etc/cider-ci/traits.yml
      tags:
        - custom_traits

  roles:

  - role: os-setup
    tags: [os-setup]

  - role: debug
    tags: [debug]

  - role: traits/ansible
    when: ci_executor_trait_ansible
    tags: ci_executor_trait_ansible

  - role: traits/apache2
    when: ci_executor_trait_apache2
    tags: ci_executor_trait_apache2

  - role: traits/bower
    when: ci_executor_trait_bower
    tags: ci_executor_trait_bower

  - role: traits/chruby
    when: ci_executor_trait_chruby
    tags: ci_executor_trait_chruby

  - role: traits/docker
    when: ci_executor_trait_docker
    tags: ci_executor_trait_docker

  - role: traits/git-crypt
    when: ci_executor_trait_git_crypt
    tags: ci_executor_trait_git_crypt

  - role: traits/gpg
    when: ci_executor_trait_gpg
    tags: ci_executor_trait_gpg

  - role: traits/firefox-esr
    when: ci_executor_trait_firefox_esr
    tags: ci_executor_trait_firefox_esr

  - role: traits/firefox-esr
    vars:
      ci_executor_trait_firefox_esr_default: false
      ci_executor_trait_firefox_esr_version_major: 45
      ci_executor_trait_firefox_esr_version_minor: 9
      ci_executor_trait_firefox_esr_version_patch: 0
    tags: ci_executor_trait_firefox_esr_45

  - role: traits/firefox-esr
    vars:
      ci_executor_trait_firefox_esr_default: false
      ci_executor_trait_firefox_esr_version_major: 60
      ci_executor_trait_firefox_esr_version_minor: 4
      ci_executor_trait_firefox_esr_version_patch: 0
    tags: ci_executor_trait_firefox_esr_60

  - role: traits/firefox-esr
    vars:
      ci_executor_trait_firefox_esr_default: false
      ci_executor_trait_firefox_esr_version_major: 68
      ci_executor_trait_firefox_esr_version_minor: 12
      ci_executor_trait_firefox_esr_version_patch: 0
    tags: ci_executor_trait_firefox_esr_68

  - role: traits/firefox-esr
    vars:
      ci_executor_trait_firefox_esr_default: false
      ci_executor_trait_firefox_esr_version_major: 78
      ci_executor_trait_firefox_esr_version_minor: 3
      ci_executor_trait_firefox_esr_version_patch: 1
    tags: ci_executor_trait_firefox_esr_78


  - role: traits/leiningen
    when: ci_executor_trait_leiningen
    tags: ci_executor_trait_leiningen

  - role: traits/lxd
    when: ci_executor_trait_lxd
    tags: ci_executor_trait_lxd

  - role: traits/misc
    when: ci_executor_trait_misc
    tags: ci_executor_trait_misc

#  - role: traits/mysql
#    when: ci_executor_trait_mysql
#    tags: ci_executor_trait_mysql

  - role: traits/nvm
    when: ci_executor_trait_nvm
    tags: ci_executor_trait_nvm

  - role: traits/nodejs
    when: ci_executor_trait_nodejs
    tags: ci_executor_trait_nodejs

  - role: traits/openjdk
    when: ci_executor_trait_openjdk
    tags: ci_executor_trait_openjdk

  - role: traits/phantomjs
    when: ci_executor_trait_phantomjs
    tags: ci_executor_trait_phantomjs

  - role: traits/postgresql9
    when: ci_executor_trait_postgresql9
    tags: ci_executor_trait_postgresql9

  - role: traits/postgresql1x
    vars:
      ci_executor_trait_postgresql_version_major: 10
    when: ci_executor_trait_postgresql10
    tags: ci_executor_trait_postgresql10

  - role: traits/postgresql1x
    vars:
      ci_executor_trait_postgresql_version_major: 11
    when: ci_executor_trait_postgresql11
    tags: ci_executor_trait_postgresql11

  - role: traits/python3.8
    when: ci_executor_trait_python38
    tags: ci_executor_trait_python38

  - role: traits/rbenv
    when: ci_executor_trait_rbenv
    tags: ci_executor_trait_rbenv

  - role: traits/ruby-install
    when: ci_executor_trait_ruby_install
    tags: ci_executor_trait_ruby_install

  - role: traits/s3-cache
    when: ci_executor_trait_s3_cache
    tags: ci_executor_trait_s3_cache

  - role: traits/sqlite
    when: ci_executor_trait_sqlite
    tags: ci_executor_trait_sqlite

  - role: traits/ssh-keys
    when: ci_executor_trait_ssh_keys
    tags: ci_executor_trait_ssh_keys

  - role: traits/stress-ng
    when: ci_executor_trait_stress_ng
    tags: ci_executor_trait_stress_ng

  - role: traits/translation-tools
    when: ci_executor_trait_translation_tools
    tags: ci_executor_trait_translation_tools

  - role: traits/ubuntu-desktop
    when: ci_executor_trait_ubuntu_desktop
    tags: ci_executor_trait_ubuntu_desktop

  - role: traits/vagrant
    when: ci_executor_trait_vagrant
    tags: ci_executor_trait_vagrant

  - role: traits/virtualbox
    when: ci_executor_trait_virtualbox
    tags: ci_executor_trait_virtualbox

  - role: traits/xorg
    when: ci_executor_trait_xorg
    tags: ci_executor_trait_xorg

  - role: traits/wine
    when: ci_executor_trait_wine
    tags: ci_executor_trait_wine
