# clean services and configuration

- apt:
    pkg: sudo
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- stat:
    path: /var/local/cider-ci/.git
  register: pre_37_deploy

- set_fact:
    clean_slate: true
  when: pre_37_deploy.stat.exists

- shell: |
    rm -rf /etc/ansible
    rm -rf /etc/init/cider-ci*
    rm -rf /etc/systemd/system/cider-ci*
    rm -rf /etc/cider-ci*
    rm -rf /usr/local/bin/cider-ci*
    rm -rf /var/local/cider-ci
    exit 0
  when: clean_slate

# restart will ensure that all of our now removed services are stopped and gone

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
  when: clean_slate

- local_action: wait_for host={{ inventory_hostname }}
                port=22
                delay=10
                timeout=90
                state=started
  ignore_errors: true
  sudo: false
  when: clean_slate

# clean all the rest: logfiles, code
- shell: |
    rm -rf /var/local/cider-ci*
    rm -rf /var/log/cider-ci*
  when: clean_slate

