# specify the official hostname; it will be used in links an so on
ci_virtual_hosts:
- hostname: ci.zhdk.ch
  ssl_certificate_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
  ssl_certificate_key_file: /etc/ssl/private/ssl-cert-snakeoil.key


# take db backups every night
db_backups_enabled: True

job_retention_duration: 30 Days
