#- name: remove firefox snap package
#  snap:
#    name: firefox
#    state: absent

#- name: add firefox ppa
#  apt_repository:
#    repo: 'ppa:mozillateam/ppa'
#    state: present
#
- name: install firefox-esr
  apt:
    pkg:
      - firefox-esr
      - xauth
      - libgtk-3-0
      # - firefox-esr-geckodriver
    install_recommends: true
    update_cache: yes
    cache_valid_time: 3600

- name: register trait
  register_traits:
    traits:
      - 'Firefox-ESR'
    file: /cider-ci/executor/config/traits.yml
