job_retention_duration: "{{job_retention_duration}}"

database:
  adapter: "postgresql"
  classname: "org.postgresl.Driver"
  subname: '//localhost:{{database.port}}/{{database.name}}'
  subprotocol: "postgresql"
  user: "{{database.user}}"
  password: "{{database.password}}"
  max_pool_size: 3

github_authtoken: {{github_authtoken | default('NULL',true) }}

hostname: "{{server_http_host_name}}"

secret: "{{secret_key_base}}"

basic_auth:
  username: service
  password: "{{services_basic_auth_secret}}"

session:
  secret: "{{secret_key_base}}"

messaging:
  connection:
    vhost: cider-ci_production
    host: 127.0.0.1
    username: cider-ci_production
    password: "{{cider_ci_mq_secret}}"


server_base_url: "https://{{server_http_host_name}}"

services:

  api:

    http:
      host: localhost
      port: 8885
      context: /cider-ci
      sub_context: /api
      ssl: false

    nrepl:
      port: 7885
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database:
      max_pool_size: 20

  builder:

    http:
      host: 127.0.0.1
      port: 8884
      context: /cider-ci
      sub_context: /builder
      ssl: false

    nrepl:
      port: 7884
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database:
      max_pool_size: 10


  dispatcher:

    http:
      host: "127.0.0.1"
      port: 8882
      context: '/cider-ci'
      sub_context: '/dispatcher'
      ssl: false

    nrepl:
      port: 7882
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database:
      max_pool_size: 30

    dispatch_interval: 0.25



  notifier:

    http:
      host: 127.0.0.1
      port: 8887
      context: /cider-ci
      sub_context: /notifier
      ssl: false

    nrepl:
      port: 7887
      bind: "127.0.0.1"
      enabled: true

    database:
      max_pool_size: 10


  repository:

    http:
      host: 127.0.0.1
      port: 8881
      context: /cider-ci
      sub_context: /repositories
      ssl: false

    nrepl:
      port: 7881
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database:
      max_pool_size: 20

    repositories:
      path: "/tmp/cider-ci_repositories"


  storage:

    http:
      host: localhost
      port: 8886
      context: /cider-ci
      sub_context: /storage
      ssl: false

    nrepl:
      port: 7886
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database:
      max_pool_size: 10

    stores:

      - url_path_prefix: "/trial-attachments"
        file_path: "{{trial_attachments_path}}"
        db_table: trial_attachments

      - url_path_prefix: "/tree-attachments"
        file_path: "{{tree_attachments_path}}"
        db_table: tree_attachments


  ui:

    http:
      host: localhost
      port: 8880
      context: /cider-ci
      sub_context: /ui
      ssl: false


# configuration for the reverse proxy for dev and test, not used in production
reverse_proxy:

  http:
    host: localhost
    port: 8888
    ssl: false

  nrepl:
    port: 7888
    bind: "127.0.0.1"
    enabled: true


