os:
  - linux
  - osx

language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install shunit2 zsh ruby

before_script:
  - sudo rm -rf $HOME/.rvm $HOME/.rvmrc /etc/rvmrc /etc/profile.d/rvm.sh /usr/local/rvm /usr/local/bin/rvm
  - __rvm_unload

script: make test
