---
- name: Ensure SSH dir is around
  file: path=~/.ssh state=directory
  sudo: yes
  sudo_user: "{{user}}"

- name: Own SSH public key
  template: src=id_rsa.pub dest=~/.ssh/id_rsa.pub
  sudo: yes
  sudo_user: "{{user}}"

- name: Own SSH private key
  template: src=id_rsa dest=~/.ssh/id_rsa mode=0600
  sudo: yes
  sudo_user: "{{user}}"
