- name: Install dependencies
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: [graphviz,]
  tags: [internet]

- name: create cider-ci group
  group:
    name: cider-ci
    system: yes

- name: create cider-ci user
  user:
    name: cider-ci
    group: cider-ci

- name: unmonitor every cider-ci service
  command: rm -f /etc/monit/conf.d/cider-ci_*

- name: stop monitoring
  service:
    name: monit
    state: stopped

- name: stop every cider-ci_* service
  command: systemctl stop cider-ci_*
  failed_when: false

- name: clean systemd service files
  command: rm -f /etc/systemd/system/cider-ci*
  when: ci_clean_slate

- name: reload systemctl
  command: systemctl daemon-reload
  changed_when: false

- name: clean cider-ci base directory
  command: rm -f /etc/systemd/system/cider-ci*
  when: ci_clean_slate
