allow_duplicates: yes

dependencies:
  - role: install_nodejs

  - role: rbenv
    user: "{{user_interface_user}}"

  - role: rbenv-ruby
    user: "{{user_interface_user}}"
    ruby: '{{rubies.jruby}}'

  - role: rbenv-ruby
    user: '{{user_interface_user}}'
    ruby: '{{rubies.mri}}'


