tasks:
  build:
    traits:
      cider-ci_deploy-repo-decryption: yes
      Leiningen: yes
      git-crypt: yes
    tree_attachments:
      archive:
        content_type: application/gzip
        include_match: ^cider-ci\.tar\.gz$
      signature:
        content_type: application/octet-stream
        include_match: ^cider-ci\.tar\.gz\.sig$
    git_options:
      submodules:
        include_match: ^.*$
    scripts:
      unlock:
        body: |
          git crypt unlock
          git submodule foreach 'git crypt unlock || exit 0'
      prepare:
        body: |
          set -eux
          cd lein-dev-plugin
          lein install
      build:
        timeout: 20 Minutes
        start_when:
          prepared:
            script_key: prepare
          unlocked:
            script_key: unlock
        body: |
          set -eux
          cd deploy
          ./bin/archive-build
          ./bin/archive-sign
          cp cider-ci.tar.gz* ../.
