#!/bin/sh
xrdb {{user_home}}/.Xresources
xsetroot -solid grey
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
# Fix to make GNOME work
fluxbox &
export XKL_XMODMAP_DISABLE=1
/etc/X11/Xsession

