- include: install.yml
  tags: [deploy-install]

- include: configure.yml
  tags: [configure]

- include: setup-database.yml
  tags: [deploy-setup-database]

- name: remove old systemd service
  file:
     path: /etc/systemd/system/cider-ci_{{item}}.service
     state: absent
  with_items: [api, builder, dispatcher, repository, storage, server]

- include: setup-service.yml
  with_dict: '{{ci_server_services}}'
  tags: [deploy-setup-services]

- name: define server service
  template:
    src: server.service
    dest: /etc/systemd/system/cider-ci_server.service

- name: working dir for server service
  file:
    path: /cider-ci/server/server/log/
    owner: cider-ci
    state: directory

- name: define server service
  template:
    src: server.service
    dest: /etc/systemd/system/cider-ci_server.service

- name: reload systemctl
  command: systemctl daemon-reload
  changed_when: false

- name: start service {{item.value.name}}
  service:
    name: cider-ci_{{item.value.name}}
    state: restarted
    enabled: yes
  with_dict: '{{ci_server_services}}'

- name: wait for service {{item.value.name}}
  wait_for:
    host: localhost
    port: '{{item.value.http_port}}'
    timeout: 180
  with_dict: '{{ci_server_services}}'
