###############################################################################

- name: dependencies
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: [monit, ruby]

- hmac_sha1_signature:
    message: monit
    secret: '{{ci_master_secret}}'
  register: monit_password_signature

- set_fact:
    monit_password: '{{monit_password_signature.signature}}'

- include: monitor-service.yml
  with_dict: '{{ci_services}}'

- name: reload monit
  service:
    name: monit
    state: reloaded
