- name: the cider-ci_rabbitmq service is running
  service:
    name: cider-ci_rabbitmq
    state: started
    enabled: yes

- name: wait for service cider-ci_rabbitmq
  wait_for:
    host: localhost
    port: '{{ci_rabbitmq_node_port}}'
    timeout: 60

- rabbitmq_user:
    node: '{{ci_rabbitmq_node_name}}'
    name: cider-ci
    state: absent

- rabbitmq_vhost:
    node: '{{ci_rabbitmq_node_name}}'
    name: cider-ci_v4
    state: absent

- rabbitmq_vhost:
    node: '{{ci_rabbitmq_node_name}}'
    name: cider-ci_v4
    state: present

- rabbitmq_user:
    node: '{{ci_rabbitmq_node_name}}'
    user: cider-ci
    force: yes
    password: "{{ci_messaging_secret}}"
    vhost: cider-ci_v4
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: management
