- name: the cider-ci_postgresql service is running
  service:
    name: cider-ci_postgresql
    state: started
    enabled: yes

- name: wait for service cider-ci_postgresql
  wait_for:
    host: localhost
    port: '{{ci_server_postgres_port}}'
    timeout: 60

- name: Configure the rails database
  template:
    src: rails-database.yml
    dest: /cider-ci/server/user-interface/config/database.yml

- name: Create or update the cider-ci database role
  become_user: root
  become_method: sudo
  postgresql_user:
    password: '{{ci_server_database_secret}}'
    name: cider-ci
    role_attr_flags: CREATEDB,SUPERUSER,LOGIN
    login_user: root
    port: '{{ci_server_postgres_port}}'

- name: Create the database
  postgresql_db:
    name: cider-ci_v4
    login_host: localhost
    login_user: cider-ci
    login_password: '{{ci_server_database_secret}}'
    port: '{{ci_server_postgres_port}}'

- name: Migrate the database
  become: yes
  become_user: cider-ci
  shell: |
    #!/usr/bin/env bash
    set -eux
    cd {{ci_server_dir}}
    /usr/lib/jvm/java-8-openjdk-amd64/bin/java \
      -jar {{ci_server_dir}}/cider-ci.jar \
      server migrate \
      -d "jdbc:postgresql://cider-ci:{{ci_server_database_secret}}@localhost:{{ci_server_postgres_port}}/cider-ci_v4"
