- set_fact:
    index: '{{item.0}}'
    virtual_host: '{{item.1}}'

- template:
    src: http.conf
    dest: /etc/apache2/cider-ci/{{index}}_http.conf
    mode: 0644

- file:
    state: link
    src: /etc/apache2/cider-ci/{{index}}_http.conf
    dest: /etc/apache2/sites-enabled/cider-ci_{{index}}_http.conf

- template:
    src: https.conf
    dest: /etc/apache2/cider-ci/{{index}}_https.conf
    mode: 0644
  when: virtual_host.ssl_certificate_file is defined

- file:
    state: link
    src: /etc/apache2/cider-ci/{{index}}_https.conf
    dest: /etc/apache2/sites-enabled/cider-ci_{{index}}_https.conf
  when: virtual_host.ssl_certificate_file is defined
