ci_vim_mode: true

server_url_host: ci3.zhdk.ch
server_base_url: http://{{server_url_host}}

ci_trait_ansible: true
ci_trait_chruby: true
ci_trait_firefox_esr: true
ci_trait_leiningen: true
ci_trait_mysql: true
ci_trait_misc: true
ci_trait_nodejs: true
ci_trait_nodejs: true
ci_trait_openjdk: true
ci_trait_phantomjs: true
ci_trait_postgresql: true
ci_trait_rbenv: true
ci_trait_ruby_install: true
ci_trait_sqlite: true

authentication_providers:
  github:
    name: GitHub
    client_id: "{{github_client_id}}"
    client_secret: "{{github_client_secret}}"
    oauth_base_url: https://github.com/login/oauth
    api_endpoint: https://api.github.com
    sign-in_strategies:

    - type: team-membership
      organization-login: zhdk
      team-name: 'ci.zhdk.ch Admins'
      access_token: "{{github_zhdk_team_membership_access_token}}"
      create-attributes:
        is_admin: true
        account_enabled: true
        password_sign_in_allowed: true
        max_session_lifetime: 7 days
      update-attributes:
        is_admin: true
        account_enabled: true

    - type: organization-membership
      organization-login: Madek
      create-attributes:
        is_admin: false
        account_enabled: true
        password_sign_in_allowed: false
        max_session_lifetime: 7 days
      update-attributes:
        account_enabled: true

    - type: organization-membership
      organization-login: leihs
      create-attributes:
        is_admin: false
        account_enabled: true
        password_sign_in_allowed: false
        max_session_lifetime: 7 days
      update-attributes:
        account_enabled: true

    - type: organization-membership
      organization-login: cider-ci
      create-attributes:
        is_admin: false
        account_enabled: true
        password_sign_in_allowed: false
        max_session_lifetime: 7 days
      update-attributes:
        account_enabled: true

