- name: install gettext; translate-toolkit
  apt:
    pkg:
    - gettext
    - translate-toolkit
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- name: register traits
  register_traits:
    traits:
      - translation-tools
      - gettext
      - translate-toolkit
    file: /etc/cider-ci/traits.yml
