- include: ramdisk.yml
  tags: ramdisk
  when: ci_executor_ramdisk_setup

- name: Install dependencies
  apt:
    pkg:
    - ruby
    - curl
    - stress
    - stress-ng
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- file:
    path: /cider-ci/executor
    state: absent
  when: ci_clean_slate

- include: configure.yml
  tags: [configure]

- include: setup-downloader.yml
  tags: [executors_deploy_setup-downloader]

- include: setup-service.yml
  tags: [executors_deploy_setup-service]

- update_system_traits: {}
  tags: executors_deploy_update-system-traits

- register_traits:
    traits:
      - '{{ansible_distribution}}'
      - '{{ansible_distribution}} {{ansible_distribution_release}}'
      - '{{inventory_hostname}}'
    file: /etc/cider-ci/traits.yml

- name: daily reboot
  cron:
    name: daily-reboot
    hour: '5'
    minute: '43'
    job: '/sbin/shutdown -r now'
    cron_file: daily-reboot
    user: 'root'
  when: ci_executor_daily_reboot
  tags: [debug]

- name: daily reboot
  cron:
    cron_file: daily-reboot
    name: daily-reboot
    state: absent
  when: not ci_executor_daily_reboot
  tags: [debug]

