- name: install monit
  apt: name={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: [monit]
  tags: [internet]

- name: unmonitor
  monit:
    name: cider-ci_executor
    state: unmonitored
  failed_when: false

- name: install service
  template:
    src: cider-ci_executor.service
    dest: /etc/systemd/system/cider-ci_executor.service
    mode: 0644

- name: reload systemctl
  command: systemctl daemon-reload
  changed_when: false

- name: executor service is started
  service:
    name: cider-ci_executor
    state: restarted
    enabled: yes

#- name: configure executor monitoring
#  template:
#    src: cider-ci_executor.monit
#    dest: /etc/monit/conf.d/cider-ci_executor
#    mode: 0600
#
#- name: reload monitoring
#  service:
#    name: monit
#    state: reloaded
