- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - maven

- apt: pkg={{item}} state=absent update_cache=yes cache_valid_time=3600
  with_items:
    - maven2

- lineinfile:
    line: "{{item}}"
    dest: "{{cider_ci_traits_file}}"
    create: yes
    state: present
  with_items:
    - "- maven"
    - "- maven3"
