- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
  - python-pip
  - python-dev

- pip: name=mkdocs extra_args='--upgrade'

- file:
    path: /etc/cider-ci
    state: directory
    mode: "0755"

- lineinfile:
    line: "{{item}}"
    dest: "{{cider_ci_traits_file}}"
    create: yes
    state: present
  with_items:
    - "- mkdocs"
