
- name: copy install dir
  synchronize:
    src: files/chruby-0.3.9
    dest: /tmp/
    recursive: true
    delete: true
    checksum: true

- name: install
  shell:  |
    set -eux
    cd /tmp/chruby-0.3.9
    make install

- name: register trait
  register_traits:
    traits: [chruby]
    file: /cider-ci/executor/config/traits.yml
