- name: install xorg
  apt:
    pkg: '{{item}}'
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: yes
  with_items:
    - xserver-xorg-core
  tags: [internet]

- name: register trait
  register_traits:
    traits:
      - xorg
    file: /etc/cider-ci/traits.yml
