- name: Install dependencies
  apt:
    pkg:
    - ruby
    - pandoc
    - nodejs
    state: latests
    update_cache: yes
    cache_valid_time: 3600
  when: >
    (ansible_distribution == "Debian"
      or  ansible_distribution == "Ubuntu")

- name: build release archive
  shell: ./bin/archive-build
  tags: [debug]
