- name: Install dependencies
  apt:
    pkg: ruby
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items: [ruby]
  tags: [internet]
  when: >
    (ansible_distribution == "Debian"
      or  ansible_distribution == "Ubuntu")

- include_tasks: search_download_archive.yml

- include_tasks: build.yml
  when: download_urls is not defined
