- name: Install dependencies
  apt:
    pkg: ruby
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]
  when: >
    (ansible_distribution == "Debian"
      or  ansible_distribution == "Ubuntu")

- search_download_archive: {}
  register: search_download_archive
  tags: [debug]

- debug:
    var: search_download_archive
  tags: [debug]

- set_fact:
    download_urls: "{{search_download_archive.urls}}"
  when: >
    (search_download_archive.urls is not none)
    and (not ci_force_local_build)
  tags: [debug]

- debug:
    var: download_urls
  tags: [debug]
