- apt_repository:
    repo: deb http://http.debian.net/debian jessie-backports main contrib non-free
    state: present
    update_cache: yes
  tags: [internet]

- apt:
    name: openjdk-8-jdk
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    default_release: jessie-backports
  tags: [internet]

  # java etc is here: /usr/lib/jvm/java-8-openjdk-amd64/bin
