- include: jessie.yml
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "jessie"

- apt:
    pkg: openjdk-8-jdk
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]
  when: ansible_distribution == "Ubuntu"

