- include: jessie.yml
  when: >
    (ansible_distribution == "Debian"
      and ansible_distribution_release == "jessie")

- apt:
    name: openjdk-8-jdk
    state: latest
  tags: [internet]
  when: >
    (ansible_distribution == "Ubuntu"
    and (ansible_distribution_release == "xenial"
    or ansible_distribution_release == "bionic"))
    
