- apt: pkg={{item}} state=purge absent=yes update_cache=yes cache_valid_time=3600
  with_items: [rabbitmq-server, amqp-tools]
  tags: [internet]

- name: make sure the rabbitmq service is not running
  service:
    name: cider-ci_rabbitmq
    state: stopped
  when: ci_clean_slate
  failed_when: false

- shell: rm -rf /etc/systemd/system/cider-ci_rabbitmq.service

- shell: rm -rf /cider-ci/var/rabbitmq


