### MySQL

- name: install mysql packages
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - libmysqlclient-dev
    - '{{ci_executor_trait_mysql_variant}}-client'
    - '{{ci_executor_trait_mysql_variant}}-server'
    - python-configparser
    - python-mysqldb
  tags: [internet]

- name: setup user
  mysql_user:
    name: '{{ci_executor_exec_user}}'
    password: '{{ci_executor_exec_user}}'
    priv: '*.*:ALL'
    state: present

- name: setup env
  template:
    src: mysql_env.sh
    dest: ~{{ci_executor_exec_user}}/.bash_login.d/mysql.sh
    owner: root
    group: '{{ci_executor_exec_user}}'
    mode: 0640

- name: register postgresql trait
  register_traits:
    traits:
      - MySQL
    file: /cider-ci/executor/config/traits.yml
