# specify the official hostname; it will be used in links an so on
ci_virtual_hosts:
- hostname: ci3.zhdk.ch
  ssl_certificate_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
  ssl_certificate_key_file: /etc/ssl/private/ssl-cert-snakeoil.key


db_backups_enabled: True

# we have to switch to different port for the executor since
# the server is is using 443
executor_service_https_port: 8443

job_retention_duration: 30 Days
