- apt_repository:
    repo: 'deb https://deb.nodesource.com/node_4.x {{ansible_distribution_release}} main'
    state: present

- apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_4.x {{ansible_distribution_release}} main'
    state: present

- name: Add NodeSource repository preferences
  template:
    src: deb_nodesource_com_node.pref.2
    dest: /etc/apt/preferences.d/deb_nodesource_com_node.pref

- name: Install Node.js
  apt:
    pkg: nodejs
    state: latest
    cache_valid_time: 3600

