- apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - bison
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev

- name: Install libgdbm version according to distribution
  apt: pkg=libgdbm3 state=present update_cache=yes cache_valid_time=3600
  when: >
    (ansible_distribution == "Debian"
      and ansible_distribution_release == "stretch")

- name: Install libgdbm version according to distribution
  apt: pkg=libgdbm5 state=present update_cache=yes cache_valid_time=3600
  when: >
    (ansible_distribution == "Ubuntu"
      and ansible_distribution_release == "bionic")

- name: copy and unpack install dir
  unarchive:
    src: files/ruby-install-0.7.0.tar.gz
    dest: /tmp/
    creates: /tmp/ruby-install-0.7.0

- name: install ruby-install
  shell: |
    set -eux
    cd /tmp/ruby-install-0.7.0 || { ls -la /tmp; exit 1; }
    make install
    chmod a+x /usr/local/bin/ruby-install

- name: register trait
  register_traits:
    traits: [ruby-install]
    file: /cider-ci/executor/config/traits.yml
