- apt:
    pkg:
    - build-essential
    - bison
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install libgdbm version according to distribution
  apt:
    pkg: libgdbm3
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: >
    (ansible_distribution == "Debian"
      and ansible_distribution_release == "stretch")

- name: Install libgdbm version according to distribution
  apt:
    pkg: libgdbm5
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: >
    (ansible_distribution == "Ubuntu"
      and ansible_distribution_release == "bionic")

- name: copy and unpack install dir
  unarchive:
    src: https://github.com/postmodern/ruby-install/archive/v0.8.4.tar.gz
    remote_src: yes
    dest: /tmp

- name: install ruby-install
  shell: |
    set -eux
    cd /tmp/ruby-install-0.8.4 || { ls -la /tmp; exit 1; }
    make install

- name: register trait
  register_traits:
    traits: [ruby-install]
    file: /cider-ci/executor/config/traits.yml
