- apt:
    pkg:
    - python3
    - python3.8
    - python3-venv
    - python3.8-venv
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- name: register python3.8 trait
  register_traits:
    traits:
      - 'python3'
      - 'python3.8'
    file: /cider-ci/executor/config/traits.yml
