- include: RedHead7.yml
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version|int >= 7

- include: Debuntu.yml
  when: >
    (ansible_distribution == "Ubuntu"
      and ansible_distribution_major_version|int >= 7)

- include: Debuntu.yml
  when: >
    (ansible_distribution == "Debian"
      and ansible_distribution_major_version|int >= 8)
