- name: install aws cli
  apt:
    pkg: awscli
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: clean old config file
  file:
    path: ~ci-exec-user/.bash_login.d/s3_ci_cache.sh
    state: absent

- name: copy s3 env
  template:
    src: s3_cache.sh
    dest: ~ci-exec-user/.bash_login.d/s3_cache.sh
    owner: root
    group: ci-exec-user
    mode: 0640

- name: copy s3-cache-helper
  copy:
    src: "{{role_path}}/files/s3-cache-helper"
    dest: ~ci-exec-user/bin/s3-cache-helper
    owner: root
    group: ci-exec-user
    mode: 0750

- name: register trait
  register_traits:
    traits:
      - 'S3-Cache'
    file: /cider-ci/executor/config/traits.yml
