- name: unregister S3-Cache trait
  register_traits:
    remove_match: "S3-Cache"
    file: '{{item}}'
    traits: []

  with_items:
    - /cider-ci/executor/config/traits.yml
    - /etc/cider-ci/traits.yml

