- name: check if '/containers' exists
  stat:
    path: /containers
  register: containers_dir

- include_tasks: ubuntu.yml
  when: >
    (ansible_distribution == "Ubuntu")

- include_tasks: remove.yml
  when: >
    not (ansible_distribution == "Ubuntu")
