- name: install ruby
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: [ruby]
  tags: [internet]

- name: install or upgrade lxd
  apt:
    pkg: '{{item}}'
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    default_release: xenial-backports
    install_recommends: yes
  with_items:
    - lxd
    - lxd-client
    - lxd-tools
    - criu
  tags: [internet]

- name: configure the lxc https interface
  include: api.yml
  when: ci_executor_trait_lxd_api

- name: Add the Cider-CI exec user to the lxd group
  user:
    name: '{{ci_executor_exec_user}}'
    groups: lxd
    append: yes

- name: get the LXD version
  shell: ruby -e 'puts `lxd --version`.strip'
  register: lxd_version

- name: register LXD trait
  register_traits:
    remove_match: "^LXD.*"
    traits:
      - LXD
      - LXD {{lxd_version.stdout}}
    file: /cider-ci/executor/config/traits.yml
