- name: check the installed git-crypt version
  become: yes
  become_user: '{{ci_executor_exec_user}}'
  become_method: sudo
  shell:
    #!/bin/bash
    ~{{ci_executor_exec_user}}/bin/git-crypt --version
  changed_when: false
  register: installed_git_crypt_version
  ignore_errors: yes


- include: install.yml
  when: installed_git_crypt_version.stderr!= 'git-crypt 0.5.0'

