- name: install dependencies
  apt: name={{item}} state=latest update_cache=yes cache_valid_time=3600
  tags: [internet]
  with_items:
    - build-essential
    - openssl

- name: pre clean up
  shell: |
    #!/bin/bash
    cd /tmp
    rm -rf git-crypt*

- name: copy git-crypt to the server
  copy:
    src: git-crypt.tar.gz
    dest: /tmp/git-crypt.tar.gz

- name: unpack, compile and move binary in place
  shell: |
    #!/bin/bash
    set -eux
    cd /tmp
    tar xvfz git-crypt.tar.gz
    cd git-crypt
    make
    mv git-crypt ~{{ci_executor_exec_user}}/bin/git-crypt

- name: post clean up
  shell: |
    #!/bin/bash
    cd /tmp
    rm -rf git-crypt*

- name: register git-crypt trait
  register_traits:
    traits: [git-crypt]
    file: /cider-ci/executor/config/traits.yml
