- include: ubuntu_xenial.yml
  when: >
    (ansible_distribution == "Ubuntu"
      and ansible_distribution_release == "xenial")


- include: install-from-source.yml
  when: ansible_distribution == "Debian"
