sync_interval_pause_duration: {{executor_sync_interval_pause_duration}}

trial_retention_duration: {{executor_trial_retention_duration}}

server_base_url: "https://{{ci_virtual_hosts[0]['hostname']}}"

{% if executor_max_load is defined %}
max_load: {{executor_max_load}}
{% endif %}

nrepl:
  port: {{executor_service_nrepl_port}}
  bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
  enabled: {{executor_nrepl_enabled}}

http:
  host: "0.0.0.0"
  port: {{executor_service_http_port}}
  ssl-port: {{executor_service_https_port}}

basic_auth:
  username: {{executor_id}}
  password: {{executor_password}}

exec_user:

  {% if executor_execution_user is defined %}
  name: "{{executor_execution_user}}"
  {% endif %}

  {% if executor_execution_user_password is defined %}
  password: "{{executor_execution_user_password}}"
  {% endif %}


{% if executor_service_working_dir is defined %}
working_dir: "{{executor_service_working_dir}}"
{% endif %}

{% if executor_service_repository_dir is defined %}
git_repos_dir: "{{executor_service_repository_dir}}"
{% endif %}
