- name: install sqlite3
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - sqlite3
    - libsqlite3-dev

- name: register trait
  register_traits:
    traits:
      - SQLite
      - SQLite 3
    file: /etc/cider-ci/traits.yml
