- name: install sqlite3
  apt:
    pkg:
    - sqlite3
    - libsqlite3-dev
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- name: register trait
  register_traits:
    traits:
      - SQLite
      - SQLite 3
    file: /etc/cider-ci/traits.yml
