- name: create the asdf data directory
  file:
    path: '/home/{{ci_executor_exec_user}}/.asdf'
    state: directory
    owner: '{{ci_executor_exec_user}}'
    group: '{{ci_executor_exec_user}}'

- name: create the asdf plugin directory
  file:
    path: '/home/{{ci_executor_exec_user}}/.asdf/plugins'
    state: directory
    owner: '{{ci_executor_exec_user}}'
    group: '{{ci_executor_exec_user}}'

- name: copy and unpack release
  unarchive:
    src: https://github.com/asdf-vm/asdf/archive/refs/tags/v{{ci_executor_trait_asdf_version}}.tar.gz
    remote_src: yes
    dest: '/home/{{ci_executor_exec_user}}/.asdf'
    owner: root
    group: '{{ci_executor_exec_user}}'

- name: setup asdf ENV
  template:
    src: asdf.sh
    dest: ~{{ci_executor_exec_user}}/.bash_login.d/asdf.sh
    owner: root
    group: '{{ci_executor_exec_user}}'
    mode: 'go=rx'

- name: register trait
  register_traits:
    traits:
      - asdf
    file: /cider-ci/executor/config/traits.yml


