- name: install apache2
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - apache2
    - libapache2-mod-xsendfile
  tags: [internet]

- name: register trait
  register_traits:
    traits:
      - Apache 2
    file: /etc/cider-ci/traits.yml
