- name: install apache2
  apt:
    pkg:
    - apache2
    - libapache2-mod-xsendfile
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- name: Enable modules
  apache2_module:
    state: present
    name: '{{item}}'
  with_items: '{{trait_apache2_modules}}'

- name: register trait
  register_traits:
    traits:
      - Apache 2
    file: /etc/cider-ci/traits.yml
