default: &default
  port: '{{ci_postgres_port}}'
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 15
  username: cider-ci
  password: '{{ci_database_secret}}'
  database: cider-ci_v4

development:
  <<: *default
  pool: 1

production:
  <<: *default
  variables:
    statement_timeout: {{user_interface_statement_timeout_milliseconds | default(3000) }}


