- name: Configure APT for nodejs
  shell: curl -sL https://deb.nodesource.com/setup_16.x | bash -
  tags: [internet]

- name: Install node.js
  apt:
    pkg:
      - nodejs
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- name: update npm
  shell: npm install --global npm@latest

- name: node major version
  shell: node -p 'process.versions.node.split(".")[0]'
  register: ci_executor_trait_nodejs_major_version
  changed_when: false

- name: register nodjes trait
  register_traits:
    remove_match: "^nodejs.*"
    traits:
      - nodejs
      - nodejs {{ci_executor_trait_nodejs_major_version.stdout}}
    file: /etc/cider-ci/traits.yml

- name: register npm trait
  register_traits:
    remove_match: "^npm.*"
    traits:
      - npm
    file: /etc/cider-ci/traits.yml
