traits: 
  - ansible
  - chrome_and_chromedriver
  - curl
  - defaults
  - exiftool
  - firefox
  - firefox_esr
  - git
  - imagemagick
  - jruby_17
  - jruby_9000
  - leiningen
  - maven
  - mkdocs
  - mysql
  - nodejs
  - openjdk
  - phantomjs
  - postgresql
  - rabbitmq
  - rbenv
  - ruby_21
  - ruby_22
  - sqlite3
  - tightvnc

cider_ci_executor_max_load: "{{ ansible_processor_cores * ansible_processor_count }}"
cider_ci_executor_manual_traits:
  - "{{ansible_hostname}}"
