# handy for debugging but a security hole if `executor_nrepl_enabled` is set to true
nrepl_bind_address: 0.0.0.0

# no point in using ntp for a (probably?) virtual machine
ntp_enabled: False

# low settings so we get by with about 2G - 3G of RAM
lein_service_xmx_value: 200M
user_interface_xmx_value: 1G

# independent of the cores of the machine we need at least 2 parallel execution
# to demo a few things
cider_ci_executor_max_load: 2

# we have to switch to different port for the executor since
# the server is is using 443
executor_service_https_port: 8443
