- name: install system python
  raw: apt install python -y

- include: prepare.yml

- include: journald.yml
  when: >
    (ansible_distribution == "Debian"
      and ansible_distribution_release == "jessie")

- include: time.yml

- include: ntp.yml
  when: ci_ntp_setup
  tags: [ntp]

- include: vim.yml
  when: ci_vim_mode

- include: etckeeper.yml

- include: monit.yml

- include: vmware.yml

- include: ssh_keys.yml
