- name: install system python
  raw: apt install python -y

- include_tasks: prepare.yml

- include_tasks: journald.yml
  when: >
    (ansible_distribution == "Debian"
      and ansible_distribution_release == "jessie")

- include_tasks: time.yml

- include_tasks: ntp.yml
  when: ci_ntp_setup
  tags: [ntp]

- include_tasks: vim.yml
  when: ci_vim_mode

- include_tasks: etckeeper.yml

- include_tasks: monit.yml

- include_tasks: vmware.yml

- include_tasks:
    file: ssh_keys.yml
    apply:
      tags:
        - ssh-keys
  tags:
    - always
