- include: prepare.yml

- include: time.yml

- include: ntp.yml
  when: ci_ntp_setup
  tags: [ntp]

- include: vim.yml
  when: ci_vim_mode

- include: etckeeper.yml

- include: monit.yml

- include: vmware.yml

