- name: install vmware tools
  apt:
    pkg:
    - open-vm-tools
    - open-vm-tools-dkms
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_virtualization_type == "VMware"
  tags: [internet]


