- name: install wine
  apt:
    pkg: '{{item}}'
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: yes
  with_items:
    - wine-stable
  tags: [internet]

- name: register trait
  register_traits:
    traits:
      - wine
    file: /etc/cider-ci/traits.yml
