# {{ansible_managed}}
- hosts: localhost
  connection: local

  tasks:

  - name: wait for rabbitmq to be up
    wait_for:
      host: localhost
      port: '{{ci_trait_rabbitmq_node_port}}'
      timeout: 60
      connect_timeout: 1

  - rabbitmq_vhost:
      node: '{{ci_trait_rabbitmq_node_name}}'
      name: '{{ci_exec_user}}'
      state: present

  - rabbitmq_user:
      node: '{{ci_trait_rabbitmq_node_name}}'
      user: '{{ci_exec_user}}'
      force: yes
      password: '{{ci_exec_user}}'
      vhost: '{{ci_exec_user}}'
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present
      tags: administrator
