- name: upload archive to the server
  synchronize:
    src: "{{item}}"
    dest: /tmp/{{item}}
  when: hostvars.localhost.download_urls is not defined
  with_items:
    - cider-ci.tar.gz

- name: download archive to the server
  get_url:
    url: '{{hostvars.localhost.download_urls[0]}}'
    dest: /tmp/cider-ci.tar.gz
    force: yes
  when: hostvars.localhost.download_urls is defined

- name: download archive signature to the server
  get_url:
    url: '{{hostvars.localhost.download_urls[1]}}'
    dest: /tmp/cider-ci.tar.gz.sig
    force: yes
  when: hostvars.localhost.download_urls is defined

- name: copy public key to the server
  copy:
    src: crypto/cider-ci.pub.pem
    dest: /tmp/cider-ci.pub.pem
  when: hostvars.localhost.download_urls is defined

- name: verify archive
  shell: openssl dgst -verify /tmp/cider-ci.pub.pem -signature /tmp/cider-ci.tar.gz.sig /tmp/cider-ci.tar.gz
  when: hostvars.localhost.download_urls is defined

