- include: install.yml

- include: init.yml

- include: monitor.yml

- name: Create the a database for root
  postgresql_db:
    name: root
    login_user: root
    owner: root
    port: '{{ci_server_postgres_port}}'
