- apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: absent

- lineinfile:
    line: "{{item}}"
    dest: "{{cider_ci_traits_file}}"
    create: yes
    state: present
  with_items:
    - "- chromedriver"
