- apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    validate_certs: no

- apt_repository:  repo="deb http://dl.google.com/linux/chrome/deb/ stable main"

- apt: pkg=google-chrome-stable state=present update_cache=yes cache_valid_time=3600

- lineinfile:
    line: "{{item}}"
    dest: "{{cider_ci_traits_file}}"
    create: yes
    state: present
  with_items:
    - "- chromedriver"
    - "- chrome-browser"
