- apt:
    pkg:
      - openjdk-8-jdk
      - openjdk-11-jdk
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: set env
  template:
    src: env.sh
    dest: ~{{ci_executor_exec_user}}/.bash_login.d/opendjk.sh

- name: register trait
  register_traits:
    traits:
      - JDK
      - JDK 8
      - JDK 11
      - OpenJDK
      - Openjdk 8
      - Openjdk 11
    file: /cider-ci/executor/config/traits.yml

