- apt:
    pkg:
      - openjdk-11-jdk
    state: latest
    update_cache: yes
    cache_valid_time: 3600

#- name: set env
#  template:
#    src: env.sh
#    dest: ~{{ci_executor_exec_user}}/.bash_login.d/opendjk.sh

- name: register trait
  register_traits:
    traits:
      - JDK
      - JDK 11
      - OpenJDK
      - OpenJDK 11
    file: /cider-ci/executor/config/traits.yml

